const calander_data={
    2023:{
      1:[
            {
            day:1,
            month:"jan",
            year:"2023"
            },
            {
            day:2,
            month:"jan",
            year:"2023"
            },
            {
            day:3,
            month:"jan",
            year:"2023"
            },
            {
            day:4,
            month:"jan",
            year:"2023"
            },
            {
            day:5,
            month:"jan",
            year:"2023"
            },
            {
            day:6,
            month:"jan",
            year:"2023"
            },
            {
            day:7,
            month:"jan",
            year:"2023"
            },
            {
            day:8,
            month:"jan",
            year:"2023"
            },
            {
            day:9,
            month:"jan",
            year:"2023"
            },
            {
            day:10,
            month:"jan",
            year:"2023"
            },
            {
            day:11,
            month:"jan",
            year:"2023"
            },
            {
            day:12,
            month:"jan",
            year:"2023"
            },
            {
            day:13,
            month:"jan",
            year:"2023"
            },
            {
            day:14,
            month:"jan",
            year:"2023"
            },
            {
            day:15,
            month:"jan",
            year:"2023"
            },
            {
            day:16,
            month:"jan",
            year:"2023"
            },  
            {
            day:17,
            month:"jan",
            year:"2023"
            },
            {
            day:18,
            month:"jan",
            year:"2023"
            },
            {
            day:19,
            month:"jan",
            year:"2023"
            },
            {
            day:20,
            month:"jan",
            year:"2023"
            },
            {
            day:21,
            month:"jan",
            year:"2023"
            },
            {
            day:22,
            month:"jan",
            year:"2023"
            },
            {
            day:23,
            month:"jan",
            year:"2023"
            },
            {
            day:24,
            month:"jan",
            year:"2023"
            },
            {
            day:25,
            month:"jan",
            year:"2023"
            },
            {
            day:26,
            month:"jan",
            year:"2023"
            },
            {
            day:27,
            month:"jan",
            year:"2023"
            },
            {
            day:28,
            month:"jan",
            year:"2023"
            },
            {
            day:29,
            month:"jan",
            year:"2023"
            },


            {
            day:30,
            month:"jan",
            year:"2023"
            },
            {
            day:31,
            month:"jan",
            year:"2023"
            },
                                    
        ]
    }
}

const year=2023
const month = 1
const day = 1
console.log(calander_data[year][month][day-1]);